#! /bin/sh

files="\
brother.h \
brother_bugchk.c \
brother_bugchk.h \
brother_cmatch.c \
brother_cmatch.h \
brother_devaccs.c \
brother_devaccs.h \
brother_devinfo.c \
brother_devinfo.h \
brother_dtype.h \
brother_log.c \
brother_log.h \
brother_mfccmd.c \
brother_mfccmd.h \
brother_mfcinfo.h \
brother_misc.c \
brother_misc.h \
brother_modelinf.c \
brother_modelinf.h \
brother_scanner.c \
brother_scanner.h \
brother_netdev.c \
brother_netdev.h \
brother_advini.c \
brother_advini.h \
sane_strstatus.c \
stubs.c \
dll.c"

echo make libsane-brother
main=brother.c

srcget=0
if ! [ -e $main ];then
    cp -p -f  ../backend_src/brother2.c $main
    for file in $files; do
	cp -p -f ../backend_src/$file  $file
    done
    srcget=1
fi
make all
if [ $srcget = 1 ];then
    rm -f $main
    for file in $files; do
	rm -f $file
    done
fi
