#! /usr/bash

target="brsaneconfig"
ccflag1="-DBRSANESUFFIX=1 "

if [ "$1" = '-D' ] || [ "$1" = '-d' ];then
  ccflag2="-g -o -DMKCONFIG -idirafter ../backend_src"
else
  ccflag2="-Wall -O0 -DMKCONFIG -idirafter ../backend_src"
fi

echo "gcc $ccflag1 $ccflag2 -o $target brsaneconfig.c ../backend_src/brother_advini.c"
gcc $ccflag1 $ccflag2 -o $target brsaneconfig.c ../backend_src/brother_advini.c
